// Placeholder Firebase options.
// IMPORTANT: Replace this file with the real one generated by:
// flutterfire configure
// Or place your actual firebase_options.dart here.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return const FirebaseOptions(
        apiKey: 'REPLACE_WITH_API_KEY',
        appId: 'REPLACE_WITH_APP_ID',
        messagingSenderId: 'REPLACE_WITH_SENDER_ID',
        projectId: 'container-beverages',
        authDomain: 'REPLACE_WITH_AUTH_DOMAIN',
        storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
      );
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'REPLACE_WITH_API_KEY',
          appId: 'REPLACE_WITH_APP_ID',
          messagingSenderId: 'REPLACE_WITH_SENDER_ID',
          projectId: 'container-beverages',
          storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
        );
      case TargetPlatform.iOS:
        return const FirebaseOptions(
          apiKey: 'REPLACE_WITH_API_KEY',
          appId: 'REPLACE_WITH_APP_ID',
          messagingSenderId: 'REPLACE_WITH_SENDER_ID',
          projectId: 'container-beverages',
          storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
          iosBundleId: 'com.example.beverages',
        );
      case TargetPlatform.macOS:
        return const FirebaseOptions(
          apiKey: 'REPLACE_WITH_API_KEY',
          appId: 'REPLACE_WITH_APP_ID',
          messagingSenderId: 'REPLACE_WITH_SENDER_ID',
          projectId: 'container-beverages',
          storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
          iosBundleId: 'com.example.beverages',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      case TargetPlatform.fuchsia:
        return const FirebaseOptions(
          apiKey: 'REPLACE_WITH_API_KEY',
          appId: 'REPLACE_WITH_APP_ID',
          messagingSenderId: 'REPLACE_WITH_SENDER_ID',
          projectId: 'container-beverages',
          storageBucket: 'REPLACE_WITH_STORAGE_BUCKET',
        );
    }
  }
}

